### ISSUE TITLE
DAWPresence not work with Studio One 6.5.1

### ISSUE THREAD

**Issue by No06LuSec** [Myuuiii/DAWPresence#10]
**Describe the bug**

**To Reproduce**
1. I run Studio One (blank project)
2. Run DAWPresence.exe in Downloads folder
3. And cmd pop-up

**Expected behavior**
Hope it work like this 
![image](https://github.com/Myuuiii/DAWPresence/assets/32434689/cf8bdc8e-761d-443f-a3d6-c2ab95218b0b)

**Screenshots**
![Untitled](https://github.com/Myuuiii/DAWPresence/assets/32434689/addf58c4-3e67-4ea8-93fd-e36cee0d93c4)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version : ![image](https://github.com/Myuuiii/DAWPresence/assets/32434689/2aaf0a84-2f33-430c-93b7-51b7631eafc0)

**Comment by Myuuiii** [comment]
Hi there, I will get this sorted for you. Expect a fix soon

**Comment by Myuuiii** [comment]
A new release has been published, let me know if it works!

**Comment by No06LuSec** [comment]
![image](https://github.com/Myuuiii/DAWPresence/assets/32434689/c16574ba-9bde-480d-8eda-fb9918fb7d28)
Thanks youuuuu ♡⸜(˶˃ ᵕ ˂˶)⸝♡
