### ISSUE TITLE
Ableton Live 12 Support

### ISSUE THREAD

**Issue by onealhtml** [Myuuiii/DAWPresence#15]
Hey! Could you add support for Ableton Live 12? I'm not so good at coding to add it myself.

**Comment by Myuuiii** [comment]
Hi there! thank you for leaving the suggestion. I will try to work on it when I get to a net cafe! ☺️ It might take me a little bit because of a busy schedule, but I’ll try to have it all done before the end of the weekend

**Comment by onealhtml** [comment]
Hey, thanks!
I own it, so if you have any questions, I’ll be happy to help!
________________________________

**Comment by Myuuiii** [comment]
Hi, sorry to get back to this so late, A friend of mine has code that works for Ableton Live 12, I'll ask them if they can send it to me, it will be included in the update that also introduces the tray icon and an install script to make it run as a background service upon system start

**Comment by onealhtml** [comment]
Hello! That’s great, looking forward to download it!
________________________________

**Comment by Myuuiii** [comment]
Hi there, I have just created a pull request [here](https://github.com/Myuuiii/DAWPresence/pull/16), it contains a beta build. Could you try it and see if it detects live 12? 

It is now also a tray icon application, you can quit the app by going to the tray icons and left-clicking on it, that will shut it down.

**Comment by onealhtml** [comment]
Hey! It detects Ableton Live 12 just fine, but I can't close the application from the tray icon.

**Comment by Myuuiii** [comment]
On left click it doesn’t close? Right now there is no context menu so if left clicking doesn’t work I’ll gave to fix that in a second. SorrySincerely,MyuuiiiOn May 24, 2024, at 12:12, onealhtml ***@***.***> wrote:﻿
Hey! It detects Ableton Live 12 just fine, but I can't close the application from the tray icon.

**Comment by onealhtml** [comment]
Hello! Yes, that's it. I can't close it from the tray icon, and it doesn't change the project name when I switch them. Please feel free to contact me if you need any help.

**Comment by onealhtml** [comment]
Hey! Do you have any updates?

**Comment by Myuuiii** [comment]
I did make some progress I forgot to inform about, the tray icon will disappear. By default the new behavior will be that the DAWPresence starts when y ou first execute the program. Then if you run it again it will shut it down. This will probably be a temporary fix.

**Comment by onealhtml** [comment]
Hey! It works just fine! Thanks for taking the time to do this.

**Comment by Myuuiii** [comment]
Anytime! Happy you like the project 😄
