### ISSUE TITLE
Not showing correct DAW

### ISSUE THREAD

**Issue by redfiend** [Myuuiii/DAWPresence#17]
**Describe the bug**
Looking through the source files, this should be able to recognize Reaper and show it as my active DAW, however, the most recent release of this shows me as idling in Ableton Live.

**To Reproduce**
Run as normal.

**Expected behavior**
Expected to display me as either working in Reaper, or nothing at all if I'm not running a supported DAW.

**Desktop:**
 - OS: Windows 10 64-bit (10.0.19045)
 - Browser: Not Relevant
 - DAWPresence: beta-0.1.6
 - Discord: stable 314046
 - Reaper: v7.19 [Licensed]

Much obliged.

**Comment by Myuuiii** [comment]
thank you for sending in the issue, I think I have identified the problem, and will push an update in a little,

**Comment by Myuuiii** [comment]
Hi there, I have just pushed an update which can be downloaded from the releases tab. Could you let me know if this resolved your issue?

**Comment by redfiend** [comment]
It seems to be working fine; it does keep spitting out a message to update to the latest version (which is strange since I'm using the latest version) until I open the DAW, but it stops once Reaper is open. Much obliged for the fix.

**Comment by Myuuiii** [comment]
ah right, i see i forgot to update the version in the app. I've temporarily disabled the update checking on your version. I'm pushing a new version right now (it will fall under the same release, but the binary will be updated), once it gives you the notification again is when that update has completed

**Comment by Myuuiii** [comment]
I have updated the binary in the 0.1.7 release. This version check should now no longer pop up

**Comment by redfiend** [comment]
Checked the latest release and no longer seeing the update notification and it's working with Reaper, so everything's looking good. Much obliged.

**Comment by Myuuiii** [comment]
Anytime! Thank you! 💖
