### ISSUE TITLE
The app crashes when trying to open it while Reaper DAW is running.

### ISSUE THREAD

**Issue by sidoka-contact** [Myuuiii/DAWPresence#6]
**Describe the bug**
The app crashes when trying to open it while Reaper DAW is running.

**To Reproduce**
1. Open Reaper.
2. Open DAWPresence.

**Expected behavior**
The app should not crash.

**Screenshots**
![here](https://user-images.githubusercontent.com/85040993/223502577-a828047a-a909-4082-be0e-2a9e9ec7a13e.png)

**Desktop**
 - OS: Windows 10
 - Version: 20H2

**DAW**
- DAW: Reaper
- Version: v6.77

**Comment by Myuuiii** [comment]
Hi there, thank you for creating the issue.

This is due to the fact that I have not yet bound a Discord application to the Reaper presence. I will get on it right away for you!

**Comment by Myuuiii** [comment]
I have added the Reaper application Id and image keys. You can download the new release in the releases tab, let me know if there are any further issues!
