### ISSUE TITLE
Reaper's capitalization

### ISSUE THREAD

**Issue by GronyRalph** [Myuuiii/DAWPresence#7]
Ableton Live and FL Studio have their titles well written but REAPER says "Reaper", you can see on the website it's spelled "REAPER" or "Cockos REAPER" better but not "Reaper"
I'd appreciate if you can fix that so it looks more authentic you know, good app tho :)

**Comment by Myuuiii** [comment]
gotcha, expect a fix in a few minutes

**Comment by Myuuiii** [comment]
Updated, when you restart the software you should now see "REAPER" instead of "Reaper". You do not have to download a new release for this 💕
